name: "ðŸ­ Publish to trusted npm and GitHub Packages"

on:
  push:
    branches:
      - chore/trusted-release-5
  workflow_dispatch:

permissions:
  id-token: write
  contents: write
  packages: write

jobs:
  check-version:
    name: "ðŸ‘·â€â™€ï¸ Check version change"
    runs-on: ubuntu-latest
    outputs:
          version_changed: ${{ env.VERSION_CHANGED }}
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Check version change
        id: check_version
        run: |
          if git diff HEAD^ HEAD -- package.json | grep '"version"'; then
            echo "Version changed, continuing."
            echo "VERSION_CHANGED=true" >> $GITHUB_ENV
          else
            echo "Version not changed, skipping workflow. "
            echo "VERSION_CHANGED=true" >> $GITHUB_ENV
          fi

  build:
    needs: check-version
    if: needs.check-version.outputs.version_changed == 'true'
    name: "ðŸ‘· Install and build"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: ðŸ—ï¸ Install dependencies
        run: npm ci

      - name: ðŸ‘©â€ðŸ­ Build
        run: npm run build

      - name: ðŸ“¡ Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: mtds
          path: mtds/

  #publish-clojars:
  #  needs: check-version
  #  if: needs.check-version.outputs.version_changed == 'true'
  #  runs-on: ubuntu-latest
  #  name: ðŸ“¦ Publish to Clojars
  #  steps:
  #    - name: Dispatch event for publishing to Clojars
  #      if: env.VERSION_CHANGED == 'true'
   #     run: |
   #       curl -X POST \
   #         -H "Accept: application/vnd.github.v3+json" \
  #          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
  #          https://api.github.com/repos/mattilsynet/design/dispatches \
  #          -d '{"event_type":"npm_publish_done"}'

  tag:
    name: ðŸ·ï¸ Tag release
    needs: check-version
    if: needs.check-version.outputs.version_changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: ðŸ·ï¸ Create a new Git tag
        run: |
         VERSION=$(node -p "require('./package.json').version")
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Creating tag: $VERSION"
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag -a "$VERSION" -m "Release $VERSION"
          git push origin "$VERSION"

  publish-npm:
    name: ðŸ“¦ Publish to npm
    needs: check-version
    if: needs.check-version.outputs.version_changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          registry-url: "https://registry.npmjs.org"
      - run: npm ci
      - uses: actions/download-artifact@v4
        with:
          name: mtds
          path: mtds/
      - run: npm publish --access public --tag canary

  publish-github:
    name: ðŸ“¦ Publish to GitHub
    needs: check-version
    if: needs.check-version.outputs.version_changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          registry-url: "https://npm.pkg.github.com"
          scope: "@mattilsynet"
      - run: npm ci
      - uses: actions/download-artifact@v4
        with:
          name: mtds
          path: mtds/
      - run: npm publish --tag canary
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
